# eureka:
#   client:
    # register-with-eureka: true
    # fetch-registry: true
    # service-url:
    #   defaultZone: https://localhost:9002/eureka/
    # instance:
    #   hostname: localhost

eureka:
  client:
    secure-port-enabled: true
    secure-port: 9002
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:9002/
    tls:
      enabled: true
      key-store: classpath:cbcs_localhost.jks
      key-store-type: PKCS12
      key-store-password: hello_cbcs
      key-password: hello_cbcs
          
      trust-store: classpath:cbcs_localhost_truststore.jks
      trust-store-type: PKCS12
      trust-store-password: hello_cbcs
      #keyStore: classpath:cbcs_localhost.jks
      #trustStore: classpath:cbcs_localhost.jks
      #keyStoreType: pkcs12
      #keyStorePassword: '{cipher}hello_cbcs'
      #trustStorePassword: '{cipher}hello_cbcs'
      #keyPassword: '{cipher}hello_cbcs'
      
user:
  role: User123
  password: pass123

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/demoservice?useSSL=false&characterEncoding=UTF-8
#    initialization-mode: always
    platform: postgres
