#server:
  #port: 9021

spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/demoservice?useSSL=false&characterEncoding=UTF-8
#    initialization-mode: always
    platform: postgres
  jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            jdbc:
                lob:
                    non_contextual_creation: true

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
